Drako-FacturacionWeb/Models/USERS.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drako_FacturacionWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS
    {
        public int id { get; set; }
        public string usuario { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string correo { get; set; }
        public string clave { get; set; }
        public Nullable<int> idState { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
    
        public virtual CSTATE CSTATE { get; set; }
    }
}

Drako-FacturacionWeb/Models/ViewModels/UserViewModels.cs
using Microsoft.SqlServer.Server;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Drako_FacturacionWeb.Models.ViewModels
{
    public class UserViewModels
    {
        public int id { get; set; }

        [Required]
        [Display(Name = "Usuario")]
        [StringLength(30, ErrorMessage = "Longitud maxima es 30")]
        public string usuario { get; set; }

        [Required]
        [Display(Name = "Nombres")]
        [StringLength(30, ErrorMessage = "Longitud maxima es 30")]
        public string nombres { get; set; }

        [Required]
        [Display(Name = "Apellidos")]
        [StringLength(30,ErrorMessage = "Longitud maxima es 30")]
        public string apellidos { get; set; }

        [Required]
        [Display(Name = "Correo electronico")]
        [StringLength(150, ErrorMessage = "Longitud maxima es 150")]
        [EmailAddress]
        public string correo { get; set; }

        [Required]
        [Display(Name = "Contraseña")]
        [DataType(DataType.Password)]
        [StringLength(200, ErrorMessage = "Longitud maxima es 200")]
        public string clave { get; set; }

        [Display(Name = "Confimar contraseña")]
        [DataType(DataType.Password)]
        [Compare("clave",ErrorMessage = "Las contraseñas no son iguales")]
        public string confirmarClave { get; set; }

        [Required]
        [Display(Name = "Estatus")]
        public int idState { get; set; }

        public DateTime fechaRegistro { get; set; }

        //PROPIEDADES ADICIONALES
        public string tipoEstatus { get; set; }
        public string mensajeError { get; set; }
    }





    public class EditUserViewModels
    {
        public int id { get; set; }

        [Required]
        [Display(Name = "Usuario")]
        [StringLength(30, ErrorMessage = "Longitud maxima es 30")]
        public string usuario { get; set; }

        [Required]
        [Display(Name = "Nombres")]
        [StringLength(30, ErrorMessage = "Longitud maxima es 30")]
        public string nombres { get; set; }

        [Required]
        [Display(Name = "Apellidos")]
        [StringLength(30, ErrorMessage = "Longitud maxima es 30")]
        public string apellidos { get; set; }

        [Required]
        [Display(Name = "Correo electronico")]
        [StringLength(150, ErrorMessage = "Longitud maxima es 150")]
        [EmailAddress]
        public string correo { get; set; }

        [Display(Name = "Contraseña")]
        [DataType(DataType.Password)]
        [StringLength(200, ErrorMessage = "Longitud maxima es 200")]
        public string clave { get; set; }

        [Display(Name = "Confimar contraseña")]
        [DataType(DataType.Password)]
        [Compare("clave", ErrorMessage = "Las contraseñas no son iguales")]
        public string confirmarClave { get; set; }

        [Required]
        [Display(Name = "Estatus")]
        public int idState { get; set; }

        public DateTime fechaRegistro { get; set; }

        //PROPIEDADES ADICIONALES
        public string tipoEstatus { get; set; }
        public string mensajeError { get; set; }
    }
}

Drako-FacturacionWeb/Controllers/ControlController.cs
using Drako_FacturacionWeb.Models;
using Drako_FacturacionWeb.Models.TableViewModels;
using Drako_FacturacionWeb.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Drako_FacturacionWeb.Controllers
{
    public class ControlController : Controller
    {
        // GET: Control
        public ActionResult Users()
        {
            List<UserTableViewModel> lstusuario = null;
            using(var bd = new FacturacionWebEntities())
            {
                lstusuario = (from user in bd.USERS
                              join estatus in bd.CSTATE
                              on user.idState equals estatus.id
                              where user.idState == 1
                              select new UserTableViewModel
                              {
                                  id = user.id,
                                  usuario = user.usuario,
                                  nombres = user.nombres,
                                  apellidos = user.apellidos,
                                  correo = user.correo,
                                  tipoEstatus = estatus.descripcion,
                                  //idState = (int)user.idState,
                                  fechaRegistro = (DateTime)user.fechaRegistro
                              }).ToList();
            }
            return View(lstusuario);
        }

        //LLENADO DE LOS COMBO BOX 
        private void listaEstatus()
        {
            List<SelectListItem> listaEstatus;
            using (var bd = new FacturacionWebEntities())
            {
                listaEstatus = (from estatus in bd.CSTATE
                         select new SelectListItem
                         {
                             Text = estatus.descripcion,
                             Value = estatus.id.ToString()
                         }).ToList();
                listaEstatus.Insert(0, new SelectListItem { Text = "--Seleccione--", Value = "" });
                ViewBag.listaEstatus = listaEstatus;
            }
        }


        public ActionResult AddUsers()
        {
            listaEstatus();
            return View();
        }

        [HttpPost]
        public ActionResult AddUsers(UserViewModels oCLSUser)
        {
            int nregistro = 0;
            string usuario = oCLSUser.usuario;
            using(var bd = new FacturacionWebEntities())
            {
                nregistro = bd.USERS.Where(p=>p.usuario.Equals(usuario)).Count();
            }
            if(!ModelState.IsValid || nregistro >= 1)
            {
                if (nregistro >= 1) oCLSUser.mensajeError = "El usuario ya esta registrado";
                return View(oCLSUser);
            }
            else
            {
                using(var bd = new FacturacionWebEntities())
                {
                    USERS oUser = new USERS();
                    oUser.usuario = oCLSUser.usuario;
                    oUser.nombres = oCLSUser.nombres;
                    oUser.apellidos = oCLSUser.apellidos;
                    oUser.correo = oCLSUser.correo;
                    oUser.clave = oCLSUser.clave;
                    oUser.idState = 1;
                    oUser.fechaRegistro = DateTime.Now;
                    bd.USERS.Add(oUser);
                    bd.SaveChanges();
                }
            }
            return RedirectToAction("Users");
        }



        public ActionResult EditUsers(int id)
        {
            EditUserViewModels oCLSUsers = new EditUserViewModels();
            using(var bd = new FacturacionWebEntities())
            {
                listaEstatus();
                USERS oUsers = bd.USERS.Where(p=>p.id.Equals(id)).First();
                oCLSUsers.id = oUsers.id;
                oCLSUsers.usuario = oUsers.usuario;
                oCLSUsers.nombres = oUsers.nombres;
                oCLSUsers.apellidos = oUsers.apellidos;
                oCLSUsers.correo = oUsers.correo;
                oCLSUsers.clave = oUsers.clave;
                oCLSUsers.idState = (int)oUsers.idState;
                oCLSUsers.fechaRegistro = (DateTime)oUsers.fechaRegistro;
            }
            return View(oCLSUsers);
        }


        [HttpPost]
        public ActionResult EditUsers(EditUserViewModels oCLSUsers)
        {
            int nregistrado = 0;
            string ousuario = oCLSUsers.usuario;
            int oid = oCLSUsers.id;
            using(var bd = new FacturacionWebEntities())
            {
                nregistrado = bd.USERS.Where(p => p.usuario.Equals(ousuario) && !p.id.Equals(oid)).Count();
            }
            if(!ModelState.IsValid || nregistrado >= 1)
            {
                if (nregistrado >= 1) oCLSUsers.mensajeError = "El usuario ya se encuentra registrado";
                return View(oCLSUsers);
            }
            int id = oCLSUsers.id;
            using (var bd = new FacturacionWebEntities())
            {
                USERS oUsers = bd.USERS.Where(p=>p.id.Equals(id)).First();
                oUsers.id = oCLSUsers.id;
                oUsers.usuario = oCLSUsers.usuario;
                oUsers.nombres = oCLSUsers.nombres;
                oUsers.apellidos = oCLSUsers.apellidos;
                oUsers.correo = oCLSUsers.correo;
                if(oCLSUsers.clave != null && oCLSUsers.clave.Trim() != "")
                {
                    oUsers.clave = oCLSUsers.clave;
                }
                oUsers.idState = oCLSUsers.idState;
                oUsers.fechaRegistro = oCLSUsers.fechaRegistro;
                bd.SaveChanges();
            }
            return RedirectToAction("Users");
        }
    }
}

Drako-FacturacionWeb/Views/Control/AddUsers.cshtml
@using Drako_FacturacionWeb.Models.TableViewModels
@model Drako_FacturacionWeb.Models.ViewModels.UserViewModels
@{
    ViewBag.Title = "AddUsers";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<SelectListItem> listaEstatus = (List<SelectListItem>)ViewBag.listaEstatus;
}

<h2>Agregar usuario</h2>

<div class="card">
    <div class="card-header">
        <i class="fas fa-user me-1"></i> Agregar Usuario
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-6">
                @using (Html.BeginForm("AddUsers", "Control", FormMethod.Post, new { @id = "frmagregarUsuario" }))
                {
                    <div>
                        @Html.LabelFor(p => p.usuario)
                        @Html.TextBoxFor(p => p.usuario, new { @class = "form-control" })
                        @Html.ValidationMessage("usuario", new { @class = "text-danger" })
                        @if (Model != null && Model.mensajeError != null)
                        {
                            @Html.Label(Model.mensajeError, new { @class = "text-danger" })
                        }
                    </div>
                    <div>
                        @Html.LabelFor(p => p.nombres)
                        @Html.TextBoxFor(p => p.nombres, new { @class = "form-control" })
                        @Html.ValidationMessage("nombres", new { @class = "text-danger" })
                    </div>
                    <div>
                        @Html.LabelFor(p => p.apellidos)
                        @Html.TextBoxFor(p => p.apellidos, new { @class = "form-control" })
                        @Html.ValidationMessage("apellidos", new { @class = "text-danger" })
                    </div>
                    <div>
                        @Html.LabelFor(p => p.correo)
                        @Html.TextBoxFor(p => p.correo, new { @class = "form-control" })
                        @Html.ValidationMessage("correo", new { @class = "text-danger" })
                    </div>
                    <div>
                        @Html.LabelFor(p => p.clave)
                        @Html.PasswordFor(p => p.clave, new { @class = "form-control" })
                        @Html.ValidationMessage("clave", new { @class = "text-danger" })
                    </div>
                    <div>
                        @Html.LabelFor(p => p.confirmarClave)
                        @Html.PasswordFor(p => p.confirmarClave, new { @class = "form-control" })
                        @Html.ValidationMessage("confirmarClave", new { @class = "text-danger" })
                    </div>
                    <br />
                    <div style="margin:auto">
                        @*<input type="submit" class="btn btn-outline-primary" value="Guardar" />*@
                        <button type="button" class="btn btn-outline-success" data-bs-toggle="modal" data-bs-target="#exampleModal">
                            Guardar
                        </button>

                        @Html.ActionLink("Regresar", "Users", "Control", null, new { @class = "btn btn-outline-danger" })
                    </div>
                }
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Actualización del perfil</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                ¿Desea agregar el nuevo usuario?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                <button type="button" onclick="Agregar()" class="btn btn-primary">Guardar</button>
            </div>
        </div>
    </div>
</div>

<script>
    function Agregar() {
        var frmagregarUsuario = document.getElementById("frmagregarUsuario");
        frmagregarUsuario.submit();
    }
</script>

Drako-FacturacionWeb/Views/Control/EditUsers.cshtml
@using Drako_FacturacionWeb.Models.TableViewModels
@model Drako_FacturacionWeb.Models.ViewModels.EditUserViewModels
@*@model Drako_FacturacionWeb.Models.TableViewModels.UserTableViewModel*@
@{
    ViewBag.Title = "EditUsers";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<SelectListItem> listaEstatus = (List<SelectListItem>)ViewBag.listaEstatus;
}

<h2>Editar Usuarios</h2>

<div class="card">
    <div class="card-header">
        <i class="fas fa-user me-1"></i> Editar Usuario
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-6">
                @using (Html.BeginForm("EditUsers", "Control", FormMethod.Post, new { @id = "frmeditarUsuario" }))
                {
                    <div>
                        @Html.LabelFor(p => p.id)
                        @Html.TextBoxFor(p => p.id, new { @class = "form-control", ReadOnly = true })
                        @Html.ValidationMessage("id", new { @class = "text-danger" })
                    </div>
                    <div>
                        @Html.LabelFor(p => p.usuario)
                        @Html.TextBoxFor(p => p.usuario, new { @class = "form-control" })
                        @Html.ValidationMessage("usuario", new { @class = "text-danger" })
                        @if (Model != null && Model.mensajeError != null)
                        {
                            @Html.Label(Model.mensajeError, new { @class = "text-danger" })
                        }
                    </div>
                    <div>
                        @Html.LabelFor(p => p.nombres)
                        @Html.TextBoxFor(p => p.nombres, new { @class = "form-control" })
                        @Html.ValidationMessage("nombres", new { @class = "text-danger" })
                    </div>
                    <div>
                        @Html.LabelFor(p => p.apellidos)
                        @Html.TextBoxFor(p => p.apellidos, new { @class = "form-control" })
                        @Html.ValidationMessage("apellidos", new { @class = "text-danger" })
                    </div>
                    <div>
                        @Html.LabelFor(p => p.correo)
                        @Html.TextBoxFor(p => p.correo, new { @class = "form-control" })
                        @Html.ValidationMessage("correo", new { @class = "text-danger" })
                    </div>
                    <div>
                        @Html.LabelFor(p => p.clave)
                        @Html.PasswordFor(p => p.clave, new { @class = "form-control" })
                        @Html.ValidationMessage("clave", new { @class = "text-danger" })
                    </div>
                    <div>
                        @Html.LabelFor(p => p.confirmarClave)
                        @Html.PasswordFor(p => p.confirmarClave, new { @class = "form-control" })
                        @Html.ValidationMessage("confirmarClave", new { @class = "text-danger" })
                    </div>
                    <div>
                        @Html.LabelFor(p => p.idState)
                        @Html.DropDownList("idState", listaEstatus, new { @class = "form-control" })
                        @Html.ValidationMessage("tipoEstatus", new { @class = "text-danger" })
                    </div>
                    <div>
                        @Html.LabelFor(p => p.fechaRegistro)
                        @Html.TextBoxFor(p => p.fechaRegistro, new { @class = "form-control" })
                        @Html.ValidationMessage("fechaRegistro", new { @class = "text-danger" })
                    </div>
                    <br />
                    <div style="margin:auto">
                        @*<input type="submit" class="btn btn-outline-primary" value="Guardar" />*@
                        <button type="button" class="btn btn-outline-success" data-bs-toggle="modal" data-bs-target="#exampleModal">
                            Guardar
                        </button>

                        @Html.ActionLink("Regresar", "Users", "Control", null, new { @class = "btn btn-outline-danger" })
                    </div>
                }
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Actualización del perfil</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                ¿Desea guardar los cambios?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                <button type="button" onclick="Editar()" class="btn btn-primary">Guardar</button>
            </div>
        </div>
    </div>
</div>

<script>
    function Editar() {
        var frmeditarUsuario = document.getElementById("frmeditarUsuario");
        frmeditarUsuario.submit();
    }
</script>

Drako-FacturacionWeb/Views/Control/Users.cshtml
@using Drako_FacturacionWeb.Models.TableViewModels
@model List<Drako_FacturacionWeb.Models.TableViewModels.UserTableViewModel>
@{
    ViewBag.Title = "Users";
    Layout = "~/Views/Shared/_Layout.cshtml";
    //List<SelectListItem> listaEstatus = (List<SelectListItem>)ViewBag.listaEstatus;
}

<h2>Control de Usuarios</h2>

<table class="table">
    <tr>
        <td>
            <label>Usuarios</label>
        </td>
        <td>
            <a href="@Url.Action("AddUsers", "Control")" class="width: 300%;" style="text-align: right; display: inline-block; width: 100%; ">
                <botton class="btn btn-outline-primary btn-sm"><i class="fa fa-plus" aria-hidden="true" style="font-size:10px; "></i> Agregar</botton>
            </a>
        </td>
    </tr>
</table>

<br />

<div class="card">
    <div class="card-header">
        <i class="fas fa-users me-1"></i> Usuarios
    </div>
    <div class="card-body table-responsive">
        <div class="row">
            <div class="col-12">
                <table class=" table table-striped small table-responsive" width="100%">
                    <thead>
                        <tr>
                            <th>@Html.LabelFor(p => Model[0].id)</th>
                            <th>@Html.LabelFor(p => Model[0].usuario)</th>
                            <th>@Html.LabelFor(p => Model[0].nombres)</th>
                            <th>@Html.LabelFor(p => Model[0].apellidos)</th>
                            <th>@Html.LabelFor(p => Model[0].correo)</th>
                            <th>@Html.LabelFor(p => Model[0].idState)</th>
                            <th>@Html.LabelFor(p => Model[0].fechaRegistro)</th>
                            <th width="15%">Acción</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.id</td>
                                <td>@item.usuario</td>
                                <td>@item.nombres</td>
                                <td>@item.apellidos</td>
                                <td>@item.correo</td>
                                <td>@item.tipoEstatus</td>
                                <td>@item.fechaRegistro</td>
                                <td>
                                    @Html.ActionLink("Editar", "EditUsers", "Control", new { id = item.id }, new { @class = "btn btn-outline-primary btn-sm" })

                                    <button type="button" onclick="mostrarPopup(@item.id)" class="btn btn-outline-danger btn-sm" data-bs-toggle="modal" data-bs-target="#exampleModal">
                                        Eliminar
                                    </button>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
                @using (Html.BeginForm("DeleteUsers", "Control", FormMethod.Post, new { @id = "frmeliminarUsers" }))
                {
                    @Html.Hidden("txtidUsers");
                }
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Eliminación del usuario</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                ¿Deseas desactivar el usuario?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancelar</button>
                <button type="button" onclick="Eliminar()" class="btn btn-warning">Eliminar</button>
            </div>
        </div>
    </div>
</div>

<script>
    function mostrarPopup(id) {
        document.getElementById("txtidUsers").value = id;
    }
    function Eliminar() {
        var frmeliminarUsers = document.getElementById("frmeliminarUsers");
        frmeliminarUsers.submit();
    }
</script>